In [41]:
##Importing Libraries
## Libraries are ensemble of modules

import numpy as np ##allows to work with arrays
import pandas as pd ##helps us to import data sets and also create us matrix  
## Importing Dataset

dataset = pd.read_csv("Data.csv") ##we call pandas so then its function with "." then, read_csv is a pandas funciton , dataframe = certain form of data, then we put the name of the data set inside the brackets
##Now we have to create 2 new entities - 1 is the matrix of features and the another is the dependent variable vector
##Dependent variable is the last column, matrix of features are the rest of the columns
x = dataset.iloc[:,:-1].values
## x is for matrix of feature, iloc[] is a pandas function which stands for location index, it takes the indexes of the colums/rows we want to extract from the data set
## To take all the rows of the column use the colon inside which means no starting or ending, then to specify the columns we need put a comma after the colon
## To take all the columns except the last one add a new range which is ":-1", -1 in python means last column
## values is for taking all the values from the rows and columns
y  = dataset.iloc[:,-1].values
## y is for dependent variable, I put -1 for columns section instead of : because I only need that column
print(x)
print(y)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [42]:
## Taking care of missing data

##Missing data can cause some error in training ml models
##we can delete is , if dataset is large and missing data is very little
##or we can replace the missing value by the average all the available value

##scikit learn is a library used for data preprocessing
##we will be using it to handle missing data, to do this the class we will be using from it is called simpleimputer,
##we will first import he class then we will create an instance/object of that class to exactly replace the missing value byt he average of the other values,then we will have an updated dataset with new set of values
from sklearn.impute import SimpleImputer ##inorder the acceses a module we have to add a ".", simpleimputer class belongs to a module called "impute", then we import the class

##Since we are about to create a new object we need a new variable
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') ##imputer is the object of the class simpleimputer
##Then we call the respective class with tis name and then by adding "()" to call the class and assign it inside the object
##Now we can enter the right arguements
##To repalce first we have to specify what are we replacing
## So we use the arguement called missing values  to specify it then we use np.nan to deal with arrays thenwith comma we use the argument strategy which equals to mean in quotation 
## we can also use median instead of mean.
##Till now imputer is just a object, we didn't connect anythign yet to our matrix of features
imputer.fit(x[:, 1:3])##Fit method looks for missing vales and compute mean function, then to do the replacement we call another method called transform 
##1 is age column, 2 is salary column
##first call the object and then call the method called fit, the arguemet for fit method is only numerical values not the text or string
##we give x, because we need data from there
##This connects imputer to matix of features
##Now call transform method from imputer object, this method does the relacement
imputer.transform(x[:, 1:3]) ## this transform method returns the new updated version of x with the 2 replacements made
##Since transform method replaces to update x we take the updated colums and change it by what will it be returned by imputer function 
x[:,1:3] = imputer.transform(x[:, 1:3])
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [43]:
##Encoding Categorical Data

##If we see  our data set we can find one column with categories like France, spain or germany
##It would be difficult for the ml models to co-relate between these features and the outcome, so we encode them into numbers
##So we encode France into 0, spain into and germany into 2. so our ml model can understand the numerical order in these countries. But it may also interpret this this order matters but that's not the case.
##There is no relationship order between these  countries, we want our madel to avoid those so that it don't misinterpret the outcome we want to predict.
##The thing we can do is  one-hot encoding. This consited of turning this country column into 3 different columns as it has 3 categories(France,spain,germany)
##OHE consistes of creating binary vectors for each country.
##We will also replace the dependent variable values by 0 and 1

##We will use 2 class
##columntranformer class from compose module in scikit library
##another is one hot encoded class from the preprocessing module of the same scikit learn library

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [44]:
##Now create an object for the column transformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder= 'passthrough') ##We call the class to create an instance or an object, inside the paranthesis we have t0 2 enter arguements
##These arguements are first transformers where we specify what kind of transformation we want to do, which index we want to transform and the other once is remainder which will specify the columns where we won't be applying the transform.
##Now for the transformers we have to specify 3 things, first the kind of transformation (encoding), what kind of encoding (one hot, we enter the class name exactly with brackets), index of the columns we want to encode (Country column). we enter them in new square brackets
##We input them in a pair of square brackets and curved brackets(Tuple)
##for remainder we have to specify the code name that is "passthrough", this prevent other columns from ine hot encoding 
##The column transformer class has a method called fit transform which fits and transforms together to connect the object with the matrix feature
x = np.array(ct.fit_transform(x))
## we update the matrix of features by assigning it to x
##fit transform method returns x as a numpy array so it is absolutely necessary to enter x as a numpy array
##So above we have to force it fit transform to return as a numpy array we can do it by calling numpy by shortcut np,then.array which take the output of the fit transform method as it's input

print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [45]:
##Now is the dependent variable section we want to encode the values of x and y as 0 and 1
##We can do it by using another class called label encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() ##Since we are just transforming in one single columnwe don't want to enter anythign inside
y = le.fit_transform(y) ##Since this is a dependent variable this doesn't has to be a numpy array
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [46]:
##Splitting the data set into training set and tesing set

##Always apply feature scaling after splitting the data set itno training and test set
##In training set we train the machine learning model on existing observations
##In test set we evaluate the performance of the model on new observations
##Feature scaling simply consists of  scaling all your variables/features to make sure they take values in the same scale
##Why should we apply it after splitting?? It is simply because the test set is a brand new set, and feature scaling is something where we take the mean and standard deviation of the features
##and if we apply the feature scaling before splitting we would end with the mean and standard deviation of all the values including test set
##Test set is something like future data, apllying feature scaling would cause some information leakage 

##We are going to split it by a function called train_test_split from a module called model selection in scikit learn library
##This function performs 4 different sets which is x and y for training set and x and y for test set 
##x(matrix of features), y(dependent variable)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)  ## Matrix of feature sof training set, test set , dependent variable of test set and training set 
##we first enter the x and y as inputs as the arguments and for the other 2 arguements the split size(we need lot of observations in training set and comparatively less in test set) Recommended size of the split is 80% in training set and 20% in test set
##the final arguement is random_state as the observations will be split into random splits

In [47]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [48]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [49]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [50]:
print(y_test)

[0 1]


In [52]:
##Feature Scaling 

##We won't apply this for all ml models 
##2 main feature scaling tehniques are standardisation and normalisation
#Standardisation - consists od subtracting each value of the feature byt he mean fo the values of the feature and diving by standard deviation (Square root of the variance). all the values remain fron -3 to +3
##Normalisation - subtracting each value of the feature by the minimum valueof the feature ad=nd then dividing by the difference of the maximum value of the feature and the minimum value of the feature, values will be from 0 and 1

## normalisation is recommended if we have normal distribution in most of our features 
## standardisation works all the time. Therefore, we can use this everywhere and it will work

##We will do with scikit learn and with the class called standard scalar  from preprocessing module which performs standardisation

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()##we din't have any arguements to include becausewe will justv need the mean and standard deviation
##Only apply feature scaling to numerical values and not dummy variables
x_train[:,3:] = sc.fit_transform(x_train[:,3:])##I give index 3 because the index for age stars from 3 as the first 3 indexes 0 to 2 are binary encoded values of countries
print(x_train)
x_test[:,3:] = sc.transform(x_test[:,3:]) ##We only transform in test set and don't calculate the mean and standard deviation for test set
print(x_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
